pathwaze/guides/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    
    #url(r'^create/', TemplateView.as_view(template_name='guides/create.html')),
    
    #url(r'^steps/', TemplateView.as_view(template_name='guides/steps.html')),
    
    url(r'^search/', 'guides.views.search', name="search_guides"),
    
    url(r'^browse/search/$', 'guides.views.search_within_browse', name="search_within_browse"),
    url(r'^browse/$', 'guides.views.browse', name="browse"),
    url(r'^browse/(?P<slug>.*)/$', 'guides.views.browse', name="browse_guides"),
    #url(r'^browse/NUS/$', 'guides.views.search_within_NUS', name="search_within_NUS"),
    
    url(r'^(?P<slug>.*)/thank_contributor/$', 'guides.views.thank', name="thank_contributor"),
    url(r'^(?P<slug>.*)/$', 'guides.views.single', name="single_guide"),
    
    
)

pathwaze/pathwaze/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'guides.views.index', name="index"),
    url(r'^join/', TemplateView.as_view(template_name='join.html'), name="join"),
    url(r'^thanks/', TemplateView.as_view(template_name='thanks.html'), name="thanks"),

    # Examples:
    # url(r'^$', 'pathwaze.views.home', name='home'),
    # url(r'^pathwaze/', include('pathwaze.foo.urls')),
    url(r'^accounts/', include('allauth.urls')),
    
    # URL for Contributors App
    #url(r'^contributor/', include('contributors.urls')), 

    # URL for Guides App
    url(r'^guides/', include('guides.urls'), name="guides"), 

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

pathwaze/guides/models.py
from django.db import models
from django.contrib.auth.models import User

#Importing from ImageKit
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Importing base.py file to access the DEFAULT_FILE_STORAGE for image uploading
from pathwaze.settings.base import DEFAULT_FILE_STORAGE

from contributors.models import Contributor


class Guide(models.Model):
    contributor = models.ForeignKey(User)
    destination_name = models.CharField(max_length=200)
    destination_address = models.CharField(max_length=300, null=True, blank=True)
    starting_point_name = models.CharField(max_length=200)
    starting_point_address = models.CharField(max_length=300, null=True, blank=True)
    cover_image = ProcessedImageField(upload_to=DEFAULT_FILE_STORAGE + '/cover_image/', format='JPEG', options={'quality': 30}, null=True, blank=True)
    slug = models.SlugField()
    destination_lat = models.FloatField(null=True, blank=True)
    destination_long = models.FloatField(null=True, blank=True)
    starting_point_lat = models.FloatField(null=True, blank=True)
    starting_point_long = models.FloatField(null=True, blank=True)
    google_map_URL = models.URLField(max_length=300, null=True, blank=True)
    active = models.BooleanField(default=True)
    number_of_views = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __unicode__(self):
        return str(self.destination_name)
        
    def get_profile_pic(self):
        contributor = Contributor.objects.get(contributor=self.contributor)
        profile_pic = contributor.profile_pic
        return profile_pic

class Step(models.Model):
    guide = models.ForeignKey(Guide)
    step_number = models.IntegerField(default=1)
    step_image = ProcessedImageField(upload_to=DEFAULT_FILE_STORAGE + '/step_image/', format='JPEG', options={'quality': 30} , null=True, blank=True)
    step_text = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __unicode__(self):
        return str(self.step_number)
        
class Tag(models.Model):
    guide = models.ForeignKey(Guide)
    tag = models.CharField(max_length=120)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __unicode__(self):
        return self.tag
        
class Thank(models.Model):
    guide = models.ForeignKey(Guide)
    user = models.ForeignKey(User, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    
    def __unicode__(self):
        return str(self.created)
        
class Request(models.Model):
    destination_name = models.CharField(max_length=200)
    destination_address = models.CharField(max_length=300, null=True, blank=True)
    requester_email = models.EmailField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    
    def __unicode__(self):
        return self.destination_name
    
    
    
    

    

pathwaze/guides/forms.py
from django.forms import ModelForm
from .models import Request, Thank

class Request_Guide_Form(ModelForm):
    class Meta:
        model = Request

class Thank_Form(ModelForm):
    class Meta:
        model = Thank
        fields = ('guide', 'user')

pathwaze/guides/views.py
import json

from itertools import chain

from django.shortcuts import render, render_to_response, RequestContext, Http404, redirect, HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.forms.models import model_to_dict
from django.core.context_processors import csrf

from .models import Guide, Step, Tag, Thank
from .forms import Request_Guide_Form, Thank_Form
from contributors.models import Contributor

def index(request):
    guides = Guide.objects.filter(active=True).order_by('-created')
    context = {
        "guides" : guides,
    }
    return render_to_response("index.html", context, context_instance=RequestContext(request))

def browse(request):
    guides = Guide.objects.filter(active=True)
    context = {
        "guides": guides,
    }
    return render_to_response("guides/browse_all.html", context, context_instance=RequestContext(request))

#def browse(request, slug):
#    if slug == None:
#        guides = Guide.objects.filter(active=True)
#        context = {
#            "guides": guides,
#        }
#        return render_to_response("guides/browse_all.html", context, context_instance=RequestContext(request))
#    else:
#        lowercase_slug = slug.lower()
#        guides = Guide.objects.filter(active=True, tag__tag=lowercase_slug)
#        album_tag = str(slug)
#        context = {
#            "guides": guides,
#            "album_tag": album_tag,
#        }
#        return render_to_response("guides/browse_with_tag.html", context, context_instance=RequestContext(request))

def search(request):
    q = request.GET.get('q','')
    if q == None or "":
        guides = Guide.objects.filter(active=True)
    else:
        guides = Guide.objects.filter(
            Q(slug__icontains=q)|
            Q(destination_name__icontains=q)|
            Q(destination_address__icontains=q)|
            Q(tag__tag__icontains=q),
            active=True
        )
        if not guides:
            query = q
            instance_user = request.user
            request_guide_form = Request_Guide_Form(request.POST or None)
            if request_guide_form.is_valid():
                request_guide_form.save()
                return HttpResponseRedirect (reverse('browse'))
            return render_to_response("search/no_result.html", locals(), context_instance=RequestContext(request))

    return render_to_response("guides/search.html", locals(), context_instance=RequestContext(request))

def search_within_browse(request):
    q = request.GET.get('q','')
    if q == None or "":
        guides = Guide.objects.filter(active=True)
    else:
        guides = Guide.objects.filter(
            Q(slug__icontains=q)|
            Q(destination_name__icontains=q)|
            Q(destination_address__icontains=q)|
            Q(tag__tag__icontains=q),
            active=True
        )
        if not guides:
            query = q
            instance_user = request.user
            request_guide_form = Request_Guide_Form(request.POST or None)
            if request_guide_form.is_valid():
                request_guide_form.save()
                return HttpResponseRedirect (reverse('browse'))
            return render_to_response("search/no_result.html", locals(), context_instance=RequestContext(request))
            
    return render_to_response("guides/browse_all.html", locals(), context_instance=RequestContext(request))

def search_within_NUS(request):
    q = request.GET.get('q','')
    if q == None or "":
        guides = Guide.objects.filter(active=True,tag__tag="NUS")
    else:
        guides = Guide.objects.filter(
            Q(slug__icontains=q)|
            Q(destination_name__icontains=q)|
            Q(destination_address__icontains=q),
            active=True,
            tag__tag="NUS"
        )
        if not guides:
            query = q
            instance_user = request.user
            request_guide_form = Request_Guide_Form(request.POST or None)
            if request_guide_form.is_valid():
                request_guide_form.save()
                return HttpResponseRedirect(reverse('browse'))
            return render_to_response("search/no_result.html", locals(), context_instance=RequestContext(request))
    return render_to_response("guides/search.html", locals(), context_instance=RequestContext(request))

def single(request, slug):
    if slug == "browse":
        guides = Guide.objects.filter(active=True)
        context = {
            "guides": guides,
        }
        return render_to_response("guides/browse_all.html", context, context_instance=RequestContext(request))
    else:
        guide = Guide.objects.get(slug=slug)
        guide.number_of_views += 1
        guide.save()
        steps = guide.step_set.all().order_by('step_number')
        contributor = Contributor.objects.get(contributor=guide.contributor)
        if request.user.is_authenticated():
            user = request.user
        else:
            user = None
        data = {'user': user, 'guide': guide }
        thank_form = Thank_Form(request.POST or None, initial=data)
        context = {
            "guide": guide,
            "steps": steps,
            "contributor": contributor,
            "thank_form": thank_form,
        }
        return render_to_response("guides/single.html", context, context_instance=RequestContext(request))
            
def thank(request, slug):
    if request.method == 'POST':
        guide = Guide.objects.get(slug=slug)
        response_data = {}
        if request.user.is_authenticated():
            thank = Thank(guide=guide, user=request.user)
        else:
            thank = Thank(guide=guide)
        thank.save()
        
        response_data['result'] = 'Thank successful!'
        response_data['guide'] = guide.destination_name
        response_data['user'] = request.user.username
        
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

pathwaze/templates/guides/browse_all.html
{% extends 'base.html' %}

{% block content %}

<div class="grey-background">
  
    <div class="container guide-list page-content">
        <div class="row">
            <div class="col-md-7">
                <form class="form-inline" action='{% url "search_within_browse" %}'>
                    <div class="form-group">
                        <input type="text" name="q" class="form-control" id="search-bar" placeholder="Where are you heading to?">
                    </div>
                    <button type="submit" class="btn btn-default btn-pink btn-search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                </form>
            <!-- <h1>{{query}}</h1> -->
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <span class="results-summary">{{guides.count}} guides found...</span>
            </div>
            <div class="col-md-12">
                <div class="row">
                    {% for guide in guides %}
                    <div class="col-md-4 guide-card">
                        <a href= {{BASE_URL}}"/guides/{{guide.slug}}/" target='_blank'>
                            <h4 class="guide-name">{{guide.destination_name}}</h4>
                        </a>
                        <div class="guide-from">
                            <span>From: </span>
                            <span>{{guide.starting_point_name}}</span>
                        </div>
                        <a href= {{BASE_URL}}"/guides/{{guide.slug}}/" target='_blank'>
                            <div class="guide-photo">
                                <img class="cover-photo" src= {{MEDIA_URL}}{{guide.cover_image}} />
                                <span class="mapper-label">Mapped by:</span>
                                <div class="profile-photo">
                                    <img src= {{MEDIA_URL}}{{guide.get_profile_pic}} />
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block footer %}
  <div class="grey-background">
    <section class="footer"><!--Footer Bar-->
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8">
            <h5>All guides are built and contributed by our community. Let's navigate with confidence, together!</h5>
            <p>Mapping the world starting from the sunny island city of Singapore.</p> 
            <p>Made with <span class="glyphicon glyphicon-heart"></span> by Pathwaze</p>
          </div>
          <div class="col-md-4">
            <h5>Talk to us</h5>
            <span>The guy who is always getting lost:</span>
            <a href="mailto:agustiadi@pathwaze.org">agustiadi@pathwaze.org</a>
            <span>The guy who can't understand how the guy above is always lost:</span>
            <a href="mailto:joel@pathwaze.org">joel@pathwaze.org</a>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock footer %}

pathwaze/templates/guides/browse_with_tag.html
{% extends 'base.html' %}

{% load static %}

{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top" style="background-color: transparent !important">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/logo.png' %}"></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a class="contribute" href="#contribute">CONTRIBUTE GUIDE</a></li>
        <!--<li><a href="{% url 'account_signup' %}">SIGNUP</a></li>
        <li><a href="{% url 'account_login' %}">LOGIN</a></li>-->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
{% endblock navbar %}

{% block content %}
<div id="NUS-background" class="hero-background">

  <div class="container hero-content page-content">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-12">
            <h1>Navigate with Confidence, Together.</h1>
          </div>
          <div class="col-md-12">
            <h3>Nobody should ever get lost</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <form class="form-inline" action='{% url "search_within_NUS" %}'>
              <div class="form-group">
                <input type="text"  name="q" class="form-control" id="search-bar" placeholder="Where are you heading to?">
              </div>
              <button type="submit" class="btn btn-default btn-pink btn-search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
  
</div>

<div id="nav-wrapper">
  <div id="nav" class="navbar landing-navbar">
    <div class="navbar-inner">
    </div>
  </div>
</div>

<div class="grey-background">
    <div class="container guide-list page-content">        
        <div class="row">
            {% if guides %}
            <div class="col-md-12">
                <h1>{{guides.count}} guides for {{album_tag}} album</h1>
            </div>
            <div class="col-md-12">
                <div class="row">
                    {% for guide in guides %}
                    <div class="col-md-4 guide-card">
                        <a href= {{BASE_URL}}"/guides/{{guide.slug}}/" target='_blank'>
                            <h4 class="guide-name">{{guide.destination_name}}</h4>
                        </a>
                        <div class="guide-from">
                            <span>From: </span>
                            <span>{{guide.starting_point_name}}</span>
                        </div>
                        <a href= {{BASE_URL}}"/guides/{{guide.slug}}/" target='_blank'>
                            <div class="guide-photo">
                                <img class="cover-photo" src= {{MEDIA_URL}}{{guide.cover_image}} />
                                <span class="mapper-label">Mapped by:</span>
                                <div class="profile-photo">
                                    <img src= {{MEDIA_URL}}{{guide.get_profile_pic}} />
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% else %}
                <p>There is no album with this tag</p>
            {% endif %}
        </div>
       
    </div>
</div>

</div>
{% endblock content %}

{% block footer %}
  <div class="grey-background">
    <section class="footer"><!--Footer Bar-->
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8">
            <h5>All guides are built and contributed by our community. Let's navigate with confidence, together!</h5>
            <p>Mapping the world starting from the sunny island city of Singapore.</p> 
            <p>Made with <span class="glyphicon glyphicon-heart"></span> by Pathwaze</p>
          </div>
          <div class="col-md-4">
            <h5>Talk to us</h5>
            <span>The guy who is always getting lost:</span>
            <a href="mailto:agustiadi@pathwaze.org">agustiadi@pathwaze.org</a>
            <span>The guy who can't understand how the guy above is always lost:</span>
            <a href="mailto:joel@pathwaze.org">joel@pathwaze.org</a>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock footer %}

{% block extra_js %}
<script>
  $(function() {
      $('#nav-wrapper').height($("#nav").height());
      
      $('#nav').affix({
          offset: { top: $('#nav').offset().top }
      });
  });
</script>
{% endblock extra_js %}

pathwaze/templates/guides/single.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="white-background">
    <div class="container guide-header page-content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1>{{guide}}</h1>
                <span>Mapped by: </span><span class="contributor-name">{{contributor.contributor}}</span>
                <!-- <img src = {{MEDIA_URL}}{{contributor.profile_pic}} width="50" /> -->
                <!-- <h5>Created on: {{guide.created}}</h5> -->
            </div>
        </div>
    </div>
</div>
        
<div class="grey-background">
    <div class="container guide-cover-photo">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <span>{{guide.number_of_views}} views</span>
                <img src={{MEDIA_URL}}{{guide.cover_image}} />
            </div>
        </div>
    </div>
</div>        
<div class="white-background">
    <div class="container guide-content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="row guide-summary-and-map">
                    <div class="col-md-8 guide-summary">
                        <div class="guide-start">
                            <span>{{guide.starting_point_name}}</span>
                            <span>{{guide.starting_point_address}}</span>
                        </div>
                        <div class="guide-middle">
                            <img src="{% static 'images/walk.png' %}" />
                            <hr>
                        </div>
                        <div class="guide-end">
                            <span>{{guide.destination_name}}</span>
                            <span>{{guide.destination_address}}</span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div id="map"></div>
                    </div>
                </div>
                <hr>
            </div>
        </div>
        <div class="row guide-steps">
            <div class="col-md-8 col-md-offset-2">
            {% for step in steps %}
                <span class="step-number">{{step.step_number}}</span>
                <span class="step-description">{{step.step_text|urlize}}</span>
                {% if step.step_image %}
                <div class="step-image-wrapper">
                    <img class="step-image" src = {{MEDIA_URL}}{{step.step_image}} />
                </div>
                {% else %}
                    <div class="step-image"></div>
                {% endif %}
            {% endfor %}
            </div>
        </div>
        <div class="row guide-thanks">
            <div class="col-md-8 col-md-offset-2 grey-background">
                <h1>Reached!</h1>
                <form id="form_thank" method='POST' action='' enctype="multipart/form-data"> 
                    {% csrf_token %}
                    {{ thank_form.as_p }}
                    <div id="results"></div>
                    <div class="btn-thanks-hidden">
                        <button type="submit" id="thanks" class="btn btn-animate btn-thanks" /><span class="glyphicon glyphicon-heart"> </span> Thank {{contributor.contributor}}</button>
                    </div>
                    <!--<span id="thanks-cta" style="display:none">If this guide has helped you, we really hope that you will <a href="{% url 'join' %}">join our community</a> and help others by creating similar guides of places that you are familiar with!</span>-->
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div id="disqus_thread"></div>
                    <script type="text/javascript">
                    /* * * CONFIGURATION VARIABLES * * */
                    var disqus_shortname = 'pathwaze';
        
                    /* * * DON'T EDIT BELOW THIS LINE * * */
                     (function() {
                     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                     dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                     })();
                    </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
            </div>
        </div>
    </div>
</div>  

{% endblock content %}

{% block extra_js %}
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>

    $('#form_thank').on('submit', function(event){
        event.preventDefault();
        console.log("form submitted!")  // sanity check
        thank_contributor();
    });
    
    function thank_contributor() {
        console.log("thank contributor working") // sanity check
        $.ajax({
            url : "thank_contributor/", // the endpoint
            type : "POST", // http method
            data : { the_guide : $('#id_guide').val(), the_user : $('#id_user').val(), }, // data sent with the post request
    
            // handle a successful response
            success : function(json) {
                //$('#post-text').val(''); // remove the value from the input
                console.log(json); // log the returned json to the console
                console.log("success"); // another sanity check
            },
    
            // handle a non-successful response
            error : function(xhr,errmsg,err) {
                $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
            }
        });
    };
    
    // This function gets cookie with a given name
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    
    /*
    The functions below will create a header with csrftoken
    */
    
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    function sameOrigin(url) {
        // test that a given url is a same-origin URL
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }
    
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                // Send the token to same-origin, relative URLs only.
                // Send the token only if the method warrants CSRF protection
                // Using the CSRFToken value acquired earlier
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    
    $('.btn-thanks').on('click', function() {
        $(this).addClass('active');
        $(this).removeClass('btn-animate');
        // remove to redirect to thanks google form
        //document.getElementById('thanks-cta').style.cssText = 'display: block;';
        window.open(
          '{% url "thanks" %}',
          '_blank' // <- This is what makes it open in a new window.
        );
    })
    
    function initialize() {
        
        var locations = [
          ['DESCRIPTION', {{guide.destination_lat}},{{guide.destination_long}}, 2],
          ['DESCRIPTION', {{guide.starting_point_lat}},{{guide.starting_point_long}}, 1]
        ];
        
        console.log(locations)
    
        window.map = new google.maps.Map(document.getElementById('map'), {
          mapTypeId: google.maps.MapTypeId.ROADMAP
        });
    
        var bounds = new google.maps.LatLngBounds();
        var infowindow = new google.maps.InfoWindow();    
    
        for (i = 0; i < locations.length; i++) {  
          var marker = new google.maps.Marker({
            position: new google.maps.LatLng(locations[i][1], locations[i][2]),
            map: map
          });
    
          //extend the bounds to include each marker's position
          bounds.extend(marker.position);
    
          google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
              infowindow.setContent(locations[i][0]);
              infowindow.open(map, marker);
            }
          })(marker, i));
        }
        map.fitBounds(bounds);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
{% endblock extra_js %}